### ISSUE TITLE
Error with get_geometry = TRUE in getTableData

### ISSUE THREAD

**Issue by petehilljnr** [petehilljnr/rramm#6]
The problem is that the function uses a read.csv method, but the WKT has commas in it, so it is incorrectly splitting the WKT at each comma within the field, and creating new fields.  This is breaking the conversion to spatial data.

Either the WKT field is unquoted and should be quoted to avoid delimiting it, or the geometries should be handled slightly differently.

**Comment by selwyn-mccracken** [comment]
Fixed by pr #7 .
